name: Pull Request Checks
on: pull_request

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.30.3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Format check
        run: pnpm format:check
      - name: Build
        run: pnpm build
      - name: Check for diff in docs
        run: git diff --exit-code || exit 1
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      # - name: Uploading to codecov.io
      #   run: npx codecov
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
